CheerfulChomps/Controllers/CategoriesController.cs
using CheerfulChomps.Data;
using CheerfulChomps.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CheerfulChomps.Controllers
{
    //[Authorize] // authentication check: block anonymous users
    [Authorize(Roles = "Administrator")]
    public class CategoriesController : Controller
    {
        // shared db connection obj
        ApplicationDbContext _context;

        // constructor: every time controller instance created, pass in a db connection obj
        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // fetch categories from db using DbSet
            var categories = _context.Category.OrderBy(c => c.Name).ToList();

            // pass list to view for display
            return View("Index", categories);
        }

        // GET: /Categories/Create => show empty Category form
        public IActionResult Create()
        {
            return View("Create");
        }

        // POST: /Categories/Create => process form submission 
        [HttpPost]
        public IActionResult Create([Bind("Name")] Category category)
        {
            // validate input
            if (!ModelState.IsValid)
            {
                // show user the form again to fix their mistakes
                return View("Create");
            }

            // save to db using DbSet object
            _context.Category.Add(category);
            _context.SaveChanges();

            // redirect to updated list on Index
            return RedirectToAction("Index");
        }

        // GET: /Categories/Edit/27 => look up Category based on id param so user can Edit it
        public IActionResult Edit(int id)
        {
            // try to find selected Category to populate form
            var category = _context.Category.Find(id);

            if (category == null)
            {
                return View("404");
            }

            // pass category to view for display.  specify view name for clarity
            return View("Edit", category);
        }

        // POST: /Categories/Edit/27 => update Category and redirect to list
        [HttpPost]
        public IActionResult Edit([Bind("CategoryId,Name")] Category category)
        {
            // validate
            if (!ModelState.IsValid)
            {
                return View();
            }

            // save to db
            _context.Category.Update(category);
            _context.SaveChanges();

            // redirect
            return RedirectToAction("Index");
        }

        // GET: /Categories/Delete/27 => delete selected Category and refresh list
        public IActionResult Delete(int id)
        {
            var category = _context.Category.Find(id);

            if (category == null)
            {
                return View("404");
            }

            // remove from db
            _context.Category.Remove(category);
            _context.SaveChanges();

            // redirect
            return RedirectToAction("Index");
        }
    }
}

CheerfulChomps/Controllers/ProductsController.cs
using CheerfulChomps.Data;
using CheerfulChomps.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CheerfulChomps.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ProductsController : Controller
    {
        // shared db connection
        ApplicationDbContext _context;

        // constructor w/db conn dependency
        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // fetch list of products for display, joining to parent Category & sorting a-z
            var products = _context.Product
                .Include(p => p.Category)
                .OrderBy(p => p.Name)
                .ToList();

            return View(products);
        }

        // GET: /Products/Create => show empty Product form
        public IActionResult Create()
        {
            // fetch Categories a-z into dropdown list for parent selection on the form
            ViewBag.CategoryId = new SelectList(_context.Category.OrderBy(c => c.Name).ToList(), "CategoryId", "Name");

            return View();
        }

        // POST: /Products/Create => process form submission to create new Product
        [HttpPost]
        public IActionResult Create([Bind("Name,Price,Stock,Image,CategoryId")] Product product, IFormFile? Image)
        {
            // validate
            if (!ModelState.IsValid)
            {
                // fetch Categories a-z into dropdown list for parent selection on the form
                ViewBag.CategoryId = new SelectList(_context.Category.OrderBy(c => c.Name).ToList(), "CategoryId", "Name");
                return View(product);
            }

            // upload Image if any and set Image property with uniquely generated photo name
            if (Image != null)
            {
                var fileName = UploadPhoto(Image);
                product.Image = fileName;
            }

            // save to db
            _context.Product.Add(product);
            _context.SaveChanges();

            // refresh product list
            return RedirectToAction("Index");
        }

        // GET: /Products/Edit/7 => display populated Product form
        public IActionResult Edit(int id)
        {
            // find Product
            var product = _context.Product.Find(id);

            // if invalid id
            if (product == null)
            {
                return NotFound();
            }

            // fetch Categories a-z into dropdown list for parent selection on the form
            ViewBag.CategoryId = new SelectList(_context.Category.OrderBy(c => c.Name).ToList(), "CategoryId", "Name");

            // show view and pass selected Product data
            return View(product);
        }

        // POST: /Products/Edit/7 => update selected Product
        [HttpPost]
        public IActionResult Edit(int id, [Bind("ProductId,Name,Price,Stock,Image,CategoryId")] Product product, IFormFile? Image, String? CurrentImage)
        {
            // validate
            if (!ModelState.IsValid)
            {
                // fetch Categories a-z into dropdown list for parent selection on the form
                ViewBag.CategoryId = new SelectList(_context.Category.OrderBy(c => c.Name).ToList(), "CategoryId", "Name");
                return View(product);
            }

            // upload Image if any and set Image property with uniquely generated photo name
            if (Image != null)
            {
                var fileName = UploadPhoto(Image);
                product.Image = fileName;
            }
            else
            {
                // keep current Image name if there is one
                product.Image = CurrentImage;
            }

            // save to db
            _context.Product.Update(product);
            _context.SaveChanges();

            // refresh product list
            return RedirectToAction("Index");
        }

        // GET: /Products/Delete/8 => delete selected Product
        public IActionResult Delete(int id)
        {
            // find Product
            var product = _context.Product.Find(id);

            // if invalid id
            if (product == null)
            {
                return NotFound();
            }

            // delete & redirect
            _context.Product.Remove(product);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // file upload method called from both Create and Edit
        private static string UploadPhoto(IFormFile file)
        {
            // get temp location of uploaded file
            var filePath = Path.GetTempFileName();

            // use Globally Unique Identifier (GUID) to create unique name & prevent overwriting
            // food.jpg => sa89732jriusdafkj-89sdf7sa8df-food.jpg
            var fileName = Guid.NewGuid().ToString() + "-" + file.FileName;

            // get dynamic file path to target directory so it works on any server
            var uploadPath = System.IO.Directory.GetCurrentDirectory() + "\\wwwroot\\img\\products\\" + fileName;

            // execute the file copy
            using (var stream = new FileStream(uploadPath, FileMode.Create))
            {
                file.CopyTo(stream);
            }

            // return unique file name to save as part of Product record
            return fileName;
        }
    }
}

CheerfulChomps/Controllers/ShopController.cs
using CheerfulChomps.Data;
using CheerfulChomps.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.EntityFrameworkCore;
using System.Runtime.CompilerServices;
using System.Security.AccessControl;

namespace CheerfulChomps.Controllers
{
    public class ShopController : Controller
    {
        // shared db conn
        private readonly ApplicationDbContext _context;

        // config object to read vars from appsettings
        private IConfiguration _configuration;

        // enable db & configuration dependencies for this controller
        public ShopController(ApplicationDbContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            // fetch Categories from db
            var categories = _context.Category.OrderBy(c => c.Name).ToList();

            // pass list to view for display
            return View(categories);
        }

        // GET: /Shop/ByCategory/7
        public IActionResult ByCategory(int id)
        {
            // fetch products in selected category
            var products = _context.Product.Where(p => p.CategoryId == id)
                .OrderBy(p => p.Name)
                .ToList();

            // we will look up the Category by id from the db in Week 4; mock the value for now
            //ViewData["Category"] = "Category " + id.ToString();
            var category = _context.Category.Find(id);

            // ensure CategoryId is valid
            if (category == null)
            {
                return NotFound();
            }
            ViewData["Category"] = category.Name;

            return View(products);
        }

        // POST: /Shop/AddToCart => save item to user's cart in db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddToCart(int Quantity, int ProductId)
        {
            // identify customer
            var customerId = GetCustomerId();

            // look up product price
            decimal price = 0;
            var product = _context.Product.Find(ProductId);
            price = product.Price;

            // is this product already in this user's cart?
            var cartItem = _context.CartItem
                .Where(c => c.CustomerId == customerId && c.ProductId == ProductId)
                .SingleOrDefault(); // only fetch 1 record

            // customer doesn't already have this product in their cart => ADD
            if (cartItem == null)
            {
                // add item to user's cart
                var newCartItem = new CartItem
                {
                    Quantity = Quantity,
                    ProductId = ProductId,
                    CustomerId = customerId,
                    Price = price
                };

                _context.CartItem.Add(newCartItem);
            }
            else
            {
                cartItem.Quantity += Quantity;  // update quantity 
                _context.CartItem.Update(cartItem);
            }

            _context.SaveChanges();

            // redirect to cart page
            return RedirectToAction("Cart");
        }

        private string GetCustomerId()
        {
            // check for CustomerId session var
            if (HttpContext.Session.GetString("CustomerId") == null)
            {
                // if no CustomerId session var, create one using a GUID
                HttpContext.Session.SetString("CustomerId", Guid.NewGuid().ToString());
            }

            // return CustomerId session var
            return HttpContext.Session.GetString("CustomerId");
        }

        // GET: /Shop/Cart => show current user's cart
        public IActionResult Cart()
        {
            // fetch items from user's cart in db
            var cartItems = _context.CartItem
                .Include(c => c.Product) // join to parent to include Product Name in page view
                .Where(c => c.CustomerId == GetCustomerId())
                .ToList();

            // calc item total for navbar badge using Session var
            var itemCount = (from c in cartItems
                             select c.Quantity).Sum();
            HttpContext.Session.SetInt32("ItemCount", itemCount);

            return View(cartItems);
        }

        // GET: /Shop/RemoveFromCart/34 => this is obvious no?
        public IActionResult RemoveFromCart(int id)
        {
            // delete from cart
            var cartItem = _context.CartItem.Find(id);
            _context.CartItem.Remove(cartItem);
            _context.SaveChanges();

            // refresh cart
            return RedirectToAction("Cart");
        }

        // GET: /Shop/Checkout => show empty Checkout form to get Customer info
        // Customer must log in here to continue
        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        // POST: /Shop/Checkout => save order info to Session var. We'll save to db after payment.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([Bind("FirstName,LastName,Address,City,Province,PostalCode,Phone")] Order order)
        {
            // auto-fill date, total, email
            order.OrderDate = DateTime.Now;
            order.CustomerId = User.Identity.Name;
            order.OrderTotal = (from c in _context.CartItem
                                where c.CustomerId == GetCustomerId()
                                select c.Quantity * c.Price).Sum();

            // save order to Session var so we can save to db after payment
            HttpContext.Session.SetObject("Order", order);
            HttpContext.Session.SetInt32("OrderTotal", (int)(order.OrderTotal * 100));

            return RedirectToAction("SaveOrder");
        }

        // GET: /Shop/SaveOrder => save order & details, empty cart, show confirmation
        [Authorize]
        public IActionResult SaveOrder()
        {
            // create order from session var
            var order = HttpContext.Session.GetObject<Order>("Order");
            _context.Order.Add(order);
            _context.SaveChanges();

            // move cart items to order details then empty cart
            var cartItems = _context.CartItem.Where(c => c.CustomerId == GetCustomerId());
            foreach (var item in cartItems)
            {
                // create new Order Detail
                var orderDetail = new OrderDetail
                {
                    Quantity = item.Quantity,
                    ProductId = item.ProductId,
                    Price = item.Price,
                    OrderId = order.OrderId
                };

                _context.OrderDetail.Add(orderDetail);
                _context.CartItem.Remove(item);
            }
            _context.SaveChanges();

            // clear session vars (all 4)
            HttpContext.Session.Clear();

            // redirect to order confirmation => /Orders/Details/123
            return RedirectToAction("Details", "Orders",  new { @id = order.OrderId });
        }
    }
}

CheerfulChomps/Views/Shared/404.cshtml
@{
    ViewData["Title"] = "Not Found";
}
<h1>Ooops!</h1>
<p>Sorry but we couldn't find that resource.</p>

CheerfulChomps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CheerfulChomps</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CheerfulChomps.styles.css" asp-append-version="true" />
    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" alt="Cheerful Chomps Logo" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                       
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                        }                          
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Shop" asp-action="Cart">
                                Cart
                                @if (Context.Session.GetInt32("ItemCount") != null && Context.Session.GetInt32("ItemCount") > 0)
                                {
                                    <span class="badge badge-secondary">
                                        @Context.Session.GetInt32("ItemCount")
                                    </span>
                                }
                            </a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CheerfulChomps - Mateo MAtti - ID:1264118 - Exam A <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- js table sorting from https://www.kryogenix.org/code/browser/sorttable/ -->
    <script src="~/lib/sorttable/sorttable.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>